### ISSUE TITLE
Keys not being noticed

### ISSUE THREAD

**Issue by emmdel** [paulswartz/gnome-shell-grid#1]
Hi, 

I can't manage to make gnome-shell-grid working on a dual display (twinview with restricted nvidia drivers) setup.

It prints "Xlib.protocol.request.QueryExtension" and waits, the kb keys doesn't have any effect.

Could I help by providing more debug info?

Thanks,
Manu

**Comment by paulswartz** [comment]
If you add some debugging to the main loop which prints out all the received events, that would be useful.

**Comment by emmdel** [comment]
OK, inserted ala quick'n'dirty some prints. I'm not a python crack as you will see ;-)

``` python
def main():
    display = Xlib.display.Display()
    root = display.screen().root
    screen = wnck.screen_get_default()
    screen.force_update()
    (root_width, root_height) = (screen.get_width(),
                                 screen.get_height() - PANEL_HEIGHT)
    print 'root_width', root_width
    print 'root_height', root_height
    for keysym in KEYMAP:
        print 'keysym', keysym
        if keysym < XK.XK_KP_1:
            modifier_mask = KEY_MODIFIER_MASK
        else:
            modifier_mask = PAD_MODIFIER_MASK
        root.grab_key(display.keysym_to_keycode(keysym), modifier_mask, True,
                      X.GrabModeAsync, X.GrabModeAsync)
    while True:
        print 'while loop started';
        event = root.display.next_event()
        run_idle()
        if event.type == X.KeyRelease:
            print 'event.type', event.type
            run_idle()
            (root_width, root_height) = (screen.get_width(),
                                         screen.get_height() - PANEL_HEIGHT)
            w = screen.get_active_window()
            print 'w', w
            for i in range(4):
                try:
                    func = KEYMAP[display.keycode_to_keysym(event.detail, i)] 
                    break
                except KeyError:
                    continue
            else:
...
```

This prints:

> $ python gnome-shell-grid.py
> Xlib.protocol.request.QueryExtension
> root_width 3840
> root_height 1054
> keysym 104
> keysym 105
> keysym 106
> keysym 107
> keysym 108
> keysym 109
> keysym 110
> keysym 65457
> keysym 65458
> keysym 65459
> keysym 65460
> keysym 117
> keysym 65462
> keysym 65463
> keysym 65464
> keysym 65465
> while loop started

The last print is never displayed, whenether the keystrokes I'm trying

welcoming any direction to provide more useful info...

**Comment by paulswartz** [comment]
Try this:

```
    while True:
        print 'while loop started';
        event = root.display.next_event()
        print 'got event', event # added
        run_idle()
        print 'ran idle' #added
        if event.type == X.KeyRelease:
            print 'event.type', event.type
            run_idle()
        # other stuff...
```

**Comment by emmdel** [comment]
$ python gnome-shell-grid.py 

> Xlib.protocol.request.QueryExtension
> while loop started

It does never get any event...

$ uname -a

> Linux manu-work 3.0.0-13-generic-pae #22-Ubuntu SMP Wed Nov 2 15:17:35 UTC 2011 i686 athlon i386 GNU/Linux

$ setxkbmap -print

> xkb_keymap {
>   xkb_keycodes  { include "evdev+aliases(azerty)" };
>   xkb_types     { include "complete"  };
>   xkb_compat    { include "complete"  };
>   xkb_symbols   { include "pc+fr(oss)+inet(evdev)"    };
>   xkb_geometry  { include "pc(pc105)" };
> };

Using gnome-shell 3.2.1 on ubuntu 11.11

**Comment by paulswartz** [comment]
[This blog post](http://www.larsen-b.com/Article/184.html) seems to indicate that I might be missing

``` python
root.change_attributes(event_mask = X.KeyPressMask)
```

before any of the `grab_key()` calls.  Does that do anything for you?

**Comment by paulswartz** [comment]
I've added the `change_attributes` call to the script.  Is it working for you?

**Comment by emmdel** [comment]
Oh crap, sorry I missed your messages.
Had to much problems with my ATI driver and switched to Unity.

I will try when possible and report back. Thanks
