### ISSUE TITLE
Fedora Install and Support

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [paulswartz/gnome-shell-grid#3]
Any chance of getting this runnign on Fedora now that Fedora also has the Gnome 3 shell?

yum can't find a package for python-wnck

Also, on execution of script. Nothing happens.

**Comment by paulswartz** [comment]
I'm not a Fedora user, but I don't see a `python-wnck` package in their database.  You might need to install libwnck, and build the Python bindings from scratch.

**Comment by Blue-Dog-Archolite** [comment]
thanks for the response. Will let you know waht I manage and if you want you can update the install script

**Comment by Blue-Dog-Archolite** [comment]
`sudo yum install gnome-python2-libwnck python-xlib`

**Comment by paulswartz** [comment]
Thanks!
