### ISSUE TITLE
Multi-screen environment

### ISSUE THREAD

**Issue by Bugari** [paulswartz/gnome-shell-grid#9]
Unluckily, this does not work on environments with multiple screens -- on my three screen setup, "left side" is one and a half of a screen.

Sadly, it's completely unusable this way :(

**Comment by paulswartz** [comment]
This is a known issue, #2.  Unfortunately, I don't have a multi-screen environment to test in, so this needs someone with multiple screens to submit a patch.

**Comment by Bugari** [comment]
So why don't you leave this issue open? Maybe someone notices it, and will make a patch :)

**Comment by paulswartz** [comment]
Because issue #2 is already open; this is a duplicate.

**Comment by Bugari** [comment]
Oh bloody hell, you're right, I'm a retard. :P
